### ISSUE TITLE
 Invalid value for field 'resource.@'

### ISSUE THREAD

**Issue by syoyo** [lighttransport/francine#9]
Got a following error when deleting instance through `teadown.sh` script.

It looks like the instance itself was correctly deleted.

```
…

Francine: GceInstance: Finished listing all instances.
Francine: GceInstance: Start deleting all instances...
Francine: GceInstance: Deleted [https://www.googleapis.com/compute/v1/projects/lighttransport.com:computeengine/zones/asia-east1-a/instances/syoyo-master].

Francine: GceInstance: ERROR: (gcloud.compute.instances.delete) Some requests did not succeed:
 - Invalid value for field 'resource.@': '@'. Resource was not found.
```

**Comment by peryaudo** [comment]
Anyway, this is not a bug.
The main purpose of showing detail messages in deploying and teardown is debugging. I must admit that some messages are confusing, but paying too much attention to them bears no fruit.
Also, francine command line tools are not for end users. End users always interact with francine through exported APIs such as REST API and WebSocket API. So they are not that important. Please just ignore them.
